opentofu/opentofu.org

src/theme/DocPage/Layout/Sidebar.tsx
src/theme/TOC/index.tsx

fixes https://github.com/opentofu/opentofu.org/issues/174

Fix overflow-y in Doc sidebar and TOC

---

src/components/HowToSupport/index.tsx

Add links to slack and twitter in "how to support" section

---

docusaurus.config.js
src/components/Headline/index.tsx
src/components/Hero/index.tsx
src/theme/Navbar/Content/index.tsx
src/theme/NavbarItem/DefaultNavbarItem.tsx

Add roadmap and download links

---

.github/workflows/deploy-dev.yml

This should help with starting our preview workflow on forked repos.

Change dev workflow trigger event

---

src/components/TextContent/index.tsx

This fixes horizontal overflow issue on mobile screen.

Fix TextContent max-width

---

docusaurus.config.js

This enables syntax-highlighting for PowerShell snippets, one of which is included at https://opentofu.org/docs/intro/install/portable, the Windows tab.
| Before | After |
| ------ | ----- |
| ![Before](https://github.com/opentofu/opentofu.org/assets/2517560/8e8c6ae8-3363-4381-84c2-6ec8c29a4ef5) | ![After](https://github.com/opentofu/opentofu.org/assets/2517560/8aaaf5c8-e23e-404b-a104-eb578b777613) |

Syntax-highlight PowerShell code snippets

---

docusaurus.config.js

This PR fixes the docs page broken in #214.
It's broken.

Fixing broken docs entry page

---

docusaurus.config.js
src/pages/privacy.tsx

As supplied by legal.
We need one.

Privacy Policy

---

docusaurus.config.js

Add GA banner

---

.gitmodules

Updating the website with new content and switching to the v1.6 website.

Switching the website to the v1.6 branch

---

src/components/Home/index.tsx

Fixes #242: Remove latest news section try 2

---

supporters.json

Typo Cibesecurity -> Cybersecurity

---

blog/2024-03-18-help-us-test-opentofu-1-7-0-alpha1.md
blog/2024-04-18-opentofu-1-7-0-beta1.md

We are close to the release of 1.7 and are beyond beta/alpha at this point.

Remove custom 1.7.0 issue links

---

src/components/Accordion/Item.tsx
src/theme/DocItem/Layout.tsx

Related: https://github.com/opentofu/opentofu/issues/1563

fix: eslint run lint warn and error

---

faq.mdx

Removed the apostrophe.
While reading through the FAQ section, I noticed that this apostrophe is a typo. Figured I'd make a quick PR with a fix suggestion 🙏🏼

Typo fix in FAQ Page

---

blog/2024-06-24-help-us-test-opentofu-1-8-0-alpha1.md
blog/2024-07-09-opentofu-1-8-0-beta-1.md

Fix 1.8.0 blog post examples

---

blog/2024-07-09-opentofu-1-8-0-beta-1.md

Update 1.8.0-beta1 with beta2 note/links

---

README.md

As mentioned in https://github.com/opentofu/opentofu.org/pull/320, we do not clearly state that we require commits sign off in this repository. So this PR adds a sign off note to the readme.

add sign off note to the readme

---

static/slack/index.html

Fix slack link

---

docusaurus.config.ts

Announcing the OpenTofu Registry Search beta

---

blog/2025-01-10-opentofu-1-9-0.md

Text changes in the 1.9 blog post.

1.9 blog post changes

---

static/slack/index.html

We plan to use an automated tool for invites with a static link, but it still needs to be updated manually now.

update slack invite link

---

docusaurus.config.ts
src/css/custom.css

the transparent style before was difficult to view for accessibility reasons

Fixed issue where IDE was transparent on dark mode

---

blog/2025-05-19-help-us-test-opentofu-1-10-0-beta1.md
docusaurus.config.ts

Added 1.10.0-beta1 blogpost

---

src/theme/BlogListPage/index.tsx

Fix: Do not duplicate highlighted blog post

---

blog/2025-06-23-opentofu-1-10-0.md

I accidentally linked to the wrong repo. Oops!

Fixed blog post to latest tofu-ls repo
