sync-supporters.js

We have an [empty git commit error](https://github.com/opentofu/opentofu.org/actions/runs/6271263368/job/17030537566#step:6:76) produced by `lint-staged` in our sync supporters cron workflow. The reason is that we don't add empty line when generating the file, then lint-staged adds this and then throws error that there's no changes. So if we add empty line during the generation phase, we'll see no error as the GH action will not try to execute commit.

add empty line when generating supporters.json

---

src/theme/BlogPostItem/Header/Author/index.tsx

A small fix that wraps the text (author's title) if there's not enough space. Previously it would just stay on the same line.

Fix blog post's authors section on mobile resolutions

---

blog/2023-09-05-the-opentofu-fork-is-now-available.md
docusaurus.config.js
src/components/Footer/index.tsx
src/components/HowToSupport/index.tsx
static/slack/index.html

I've added a `/slack` path that will always redirect to the latest Slack invite URL, this way we'll need to change it only in one place in the future if needed.

Fix Slack URL

---

blog/2023-09-05-the-opentofu-fork-is-now-available.md
docusaurus.config.js
src/components/Footer/index.tsx
src/components/HowToSupport/index.tsx
src/components/SocialIconLink/index.tsx

Docusaurus controls the routing so when we point a link to `/slack` it will try to show a client-side route first that does not exist. We need to open these links in a new tab to skip the routing.

Fix slack link url

---

.github/workflows/deploy-dev.yml

Add `synchronize` even to the pull request trigger events so that in new commits the checks will run.
Add `synchronize` to the list of trigger evdents.
closes https://github.com/opentofu/opentofu.org/issues/202

Add synchronize to dev workflow trigger events

---

src/components/TextContent/index.tsx

Previous PR fixed max-width for smaller screens, but apparently broke Manifesto page for wider screens. Here's a fix for that.

fix max-width on wide screens

---

blog/2023-10-30-what-we-learned-with-testing-feature.md

Add missing truncate to a blogpost

---

docusaurus.config.js

This PR contains redirects for the content removed in opentofu/opentofu#859.
Let's not break links :)

Issue opentofu/opentofu#859: Redirecting old installation docs

---

Dockerfile
README.md
docker-compose.yaml

This commit adds a build container to make it easier for people without NodeJS/npm to run the website locally.
Currently, running the dev server requires a local NodeJS/npm environment, which not everyone is comfortable with. This change along with #214 makes it easy to run a local dev environment.

Adding build container

---

src/components/TextContent/index.tsx

Fixes #224
There's a specificity issue between dev and prod builds due to how Tailwind's styles are discovered. The simplest fix is to just force "our" styles as the TW's typography plugin does not allow disabling the default table styles.
I've checked links attached to the issue and they seem to work fine:
https://7d0bc05e.opentf-website.pages.dev/docs/language/syntax/json/
https://7d0bc05e.opentf-website.pages.dev/docs/language/expressions/strings/#quoted-strings

Fix horizontal padding issue in tables

---

README.md

Add cd command before git submodules command under Fetch the documentation section
The `Fetch the documentation` section doesn't include or mention changing into the cloned directory.

Add cd command before git submodules command under Fetch the documentation section

---

src/components/Home/index.tsx

Fixes #242: remove latest news section
It's broken.

Fixes #242: Remove latest news section

---

package-lock.json

A dependency(`babel/travese`) had a [critical vulnerability](https://github.com/babel/babel/security/advisories/GHSA-67hx-6x53-jw92), this PR applies the patch that fixes it.
Auto-fixed critical vulnerability by running `npm audit fix`

Fix Critical package  vulnerability

---

src/theme/Admonition/index.tsx

Admonitions is a Library that is used in the docs site to include notes, warnings and error messages. According to #222 there were no margins in the paragraphs. This PR aims to address that issue.
Fixes #222 
In the current version opentofu documentation, there are no admonitions with a code block presently that would trigger this case, so to test it successfully add the following lines to any MDX page and then try viewing it:
````
:::warning
Test `padding` for code snippets.
```
bash
echo 'Hello World'
```
:::
````
Before: 
After:

Added margins to admonition paragraphs

---

docusaurus.config.ts

Likely, this addresses the routing error that, in some cases, redirects to Error 404 when clicking on a link.
More details: https://github.com/opentofu/opentofu/issues/1116
The Docusaurus documentation suggests that this value should be either `true` or `false`. On the dev machine, links worked correctly when set to `false`.
Docs: https://docusaurus.io/docs/deployment#docusaurusconfigjs-settings

Fixes random routing errors, like here opentofu/opentofu#1116

---

docs/index.mdx
package-lock.json

This PR will resolve #276 
The order in which the 4 subsections appeared in documents section of openTofu website was not intuitive. This PR rearranges those subsection to make the page look more organised
before:
After:

rearranged the order in which 4 subsections of documents appear

---

blog/2024-03-18-help-us-test-opentofu-1-7-0-alpha1.md
blog/2024-04-18-opentofu-1-7-0-beta1.md

This PR changes hard-coded `.opentofu.pages.dev` links to relative ones in blog posts.
We redirect people from `opentofu.org` to `.opentofu.pages.dev` and this PR makes links consistent across the blog posts.

remove .pages.dev links from blog posts

---

docusaurus.config.ts

Fixes https://github.com/opentofu/opentofu.org/issues/304.
I arbitrarily chose `vsLight`; the list of available themes with the current dependencies is this, if anyone prefers something different:
```
dracula
duotoneDark
duotoneLight
github
jettwaveDark
jettwaveLight
nightOwl
nightOwlLight
oceanicNext
okaidia
oneDark
oneLight
palenight
shadesOfPurple
synthwave84
ultramin
vsDark
vsLight
```

Set both a light and a dark theme for code blocks

---

blog/2023-10-10-opentofus-new-office-hours.mdx
blog/2023-12-19-opentofu-release-candidate-is-out.md
blog/2024-03-18-help-us-test-opentofu-1-7-0-alpha1.md
blog/2024-04-18-opentofu-1-7-0-beta1.md
blog/2024-04-30-opentofu-1-7-0.md
blog/2024-06-24-help-us-test-opentofu-1-8-0-alpha1.md
blog/2024-07-09-opentofu-1-8-0-beta-1.md
blog/2024-07-29-opentofu-1-8-0.md
docusaurus.config.ts
src/components/Footer/index.tsx

Partial fix for the current "broken link" warnings, to unblock https://github.com/opentofu/opentofu.org/issues/85.
For a complete fix, separate PRs will be needed to the four branches of the main https://github.com/opentofu/opentofu repo, as there are also some broken links in each of these. Then the submodule references will need updating, and then all should be well.
Initial draft for that `main` branch is here: https://github.com/opentofu/opentofu/pull/1884/files
Fair warning in advance: once all the broken links are fixed, Docusaurus reveals further warnings about broken anchors. (The setting defaulting to `warn` for these is separate from that for the links.) But this is progress, at least.

Eliminate broken link warnings (except those from docs in the main repo)

---

docusaurus.config.ts

Fixes https://github.com/opentofu/opentofu.org/issues/85
Related to https://github.com/opentofu/opentofu/issues/1863 (potentially a fix for that, albeit may require rebuild of runner image(?))
Changes Docusaurus' config to `throw` instead of `warn`ing when it detects broken links, as all the broken links should now be fixed.
Note that fixing these links lets through new warnings about broken anchors --[`onBrokenAnchors`](https://docusaurus.io/docs/api/docusaurus-config#onBrokenAnchors) remains set to `warn`.
Follows two other PRs:
* https://github.com/opentofu/opentofu.org/pull/322
* https://github.com/opentofu/opentofu/pull/1884 and backports:
* https://github.com/opentofu/opentofu/pull/1898
* https://github.com/opentofu/opentofu/pull/1899
* https://github.com/opentofu/opentofu/pull/1915 …

Throw on broken links

---

src/components/Hero/index.tsx

OpenTofu has not been called OpenTF for awhile and is probably not necessary to point out in the hero.
Just seems like not a great use of space at this point.

Remove OpenTF reference

---

static/slack/index.html

Somehow slack removed our "forever" link I created last time...

Fix slack link

---

static/slack/index.html

We seem to have depleted the previous one. We'll need to find a better solution than manually updating this every few days, but this is just to buy us a few more days to figure that out.

Update the invite link for the Slack community

---

blog/2025-04-25-help-us-test-opentofu-1-10-0-alpha2.md
docusaurus.config.ts

This PR updates the announcement bar and changes the blog post links to point to opentofu.org dev docs.

change announcement and links for 1.10 alpha2 blog post

---

blog/2025-05-19-help-us-test-opentofu-1-10-0-beta1.md

The original version of this showed some code examples without must context on how to make use of them. This new version links to relevant documentation to try to help put these examples in context, so it's hopefully easier to figure out how and where to use them.
I also made the editorial decision to show the module call example before the provider mirror example just because far more people write their own modules than want to create mirrors of providers, and so it seems likely that the module package support will be of broader interest.
---
Since the "OCI Registry Integrations" documentation content is currently only on the `main` branch this links to the "Development" version of the docs, which is a little awkward since that URL style is a moving target that'll start to represent the …

blog/opentofu-1-10-0-beta1: More clarity on OCI Registry Support

---

blog/2025-05-19-help-us-test-opentofu-1-10-0-beta1.md

Update the blog post for the 1.10.0 beta1 release with the new experimental feature of allowing deprecation of the variables and outputs.

blog/opentofu-1-10-0-beta1: Add section about the deprecation work
